In [72]:
import pandas as pd
import numpy as np
import seaborn as sns

In [73]:
df=pd.read_csv("playstore_games_with_descriptions.csv")

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15452 entries, 0 to 15451
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                15452 non-null  int64
 1   app_name          15452 non-null  object
 2   genre             15452 non-null  object
 3   description       15452 non-null  object
 4   rating            14487 non-null  float64
 5   reviews           14487 non-null  object
 6   installs          15436 non-null  object
 7   content_rating    15452 non-null  object
 8   size              15452 non-null  object
 9   current_version   15452 non-null  object
 10  requires_android  15447 non-null  object
 11  cost_label        15434 non-null  object
 12  updated           15452 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 1.5+ MB

In [75]:
df.columns=df.columns.str.strip()

In [76]:
df.head(5)

,id,app_name,genre,description,rating,reviews,installs,content_rating,size,current_version,requires_android,cost_label,updated
0,3,Push'em all,Action,"In Push'em all, you spend your time fighting a...",3.8,"119,679 total","10,000,000+",Rated for 3+,41M,1.14,4.4 and up,Install,"April 16, 2020"
1,5,Sky Fighters 3D,Action,Play Sky Fighters 3D for fighting one-on-one. ...,4.2,"196,685 total","10,000,000+",Rated for 7+,19M,1.5,4.0 and up,Install,"May 14, 2019"
2,6,Robbery Bob,Action,"In Robbery Bob, you spend your time planning a...",4.3,"984,779 total","50,000,000+",Rated for 7+,42M,1.18.23,4.1 and up,Install,"March 25, 2020"
3,7,Shadow Fight 2,Action,"In Shadow Fight 2, you spend your time fightin...",4.6,"12,861,970 total","100,000,000+",Rated for 12+,142M,2.5.1,4.1 and up,Install,"April 15, 2020"
4,8,Cover Strike - 3D Team Shooter,Action,Cover Strike - 3D Team Shooter lets you enjoy ...,4.0,"43,322 total","10,000,000+",Rated for 12+,60M,1.2.369,4.1 and up,Install,"March 25, 2020"

In [77]:
df.drop(columns=["id","genre","rating","reviews","installs","content_rating","size","current_version","requires_android","cost_label","updated"],inplace=True)

In [78]:
df.head(5)

,app_name,description
0,Push'em all,"In Push'em all, you spend your time fighting a..."
1,Sky Fighters 3D,Play Sky Fighters 3D for fighting one-on-one. ...
2,Robbery Bob,"In Robbery Bob, you spend your time planning a..."
3,Shadow Fight 2,"In Shadow Fight 2, you spend your time fightin..."
4,Cover Strike - 3D Team Shooter,Cover Strike - 3D Team Shooter lets you enjoy ...

In [79]:
df.isnull().sum()

app_name       0
description    0
dtype: int64

In [80]:
df["NameandDecription"]=df["app_name"]+' : '+df["description"]

In [81]:
df.head(5)

,app_name,description,NameandDecription
0,Push'em all,"In Push'em all, you spend your time fighting a...","Push'em all : In Push'em all, you spend your t..."
1,Sky Fighters 3D,Play Sky Fighters 3D for fighting one-on-one. ...,Sky Fighters 3D : Play Sky Fighters 3D for fig...
2,Robbery Bob,"In Robbery Bob, you spend your time planning a...","Robbery Bob : In Robbery Bob, you spend your t..."
3,Shadow Fight 2,"In Shadow Fight 2, you spend your time fightin...","Shadow Fight 2 : In Shadow Fight 2, you spend ..."
4,Cover Strike - 3D Team Shooter,Cover Strike - 3D Team Shooter lets you enjoy ...,Cover Strike - 3D Team Shooter : Cover Strike ...

In [82]:
df.drop(columns=["description"],inplace=True)

In [83]:
df.head(5)

                                   NameandDecription
0  Push'em all : In Push'em all, you spend your t...
1  Sky Fighters 3D : Play Sky Fighters 3D for fig...
2  Robbery Bob : In Robbery Bob, you spend your t...
3  Shadow Fight 2 : In Shadow Fight 2, you spend ...
4  Cover Strike - 3D Team Shooter : Cover Strike ...